# Site settings
title: Andre Lemos
twitter_username: andrelemos2
name: Andre Lemos

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://andrelemos2.blogspot.com.br/
 - title: GitHub
   url: https://github.com/andrelemos2
 - title: LinkedIn
   url: https://br.linkedin.com/in/andre-lemos-9b16b924

#Any buzzword skills you want to include
skills:
 - Spring MVC
 - Spring Boot
 - Java
 - JPA
 - SQL
 - REST
 - Tech Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://andrelemos2.blogspot.com.br

#Work experience is required
roles:
 - title: Java Developer
   start: 2016
   end: Ongoing
   employer: Reserva Facil S/A
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Java Developer
   start: 2010
   end: 2016
   employer: Openbravo Brazil (Disoft Solutions S/A)
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> I am a senior engineer working closely with the CTO, working across the full-stack, I am involved in all aspects of the technology including the website and back-end services.
 - title: Junior Java Developer
   start: 2008
   end: 2010
   employer: Vipware Informatica Ltda
   description: A range of functional and technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level: Bachelor of Information Systems
   date: 2010
   subject: Product development and service Information Systems (IT)
   school: Bandeirante University of Sao Paulo

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/545e0dd32bcfe728cb90b48c953c917a
   courses:
    - title: Orientation object with Java
      link: https://www.coursera.org/learn/orientacao-a-objetos-com-java/home
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/9c/b444f0c97311e588123d50ccb31597/Modified--IconFinder--1454414808_1416364765_java_coffee_x_cup_application.png?auto=format&dpr=1&w=80&h=80&fit=fill&bg=FFF
      date: July 11, 2016
    - title: Introduction to Philosofy
      link: https://www.coursera.org/learn/philosophy/home/welcome
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/introphil/large-icon.png?auto=format&dpr=1&w=80&h=80&fit=fill&bg=FFF
      date: August 10, 2016

#List of interesting Github repo/projects to include - optional
github:
 - andrelemos2/learntoredux
 - andrelemos2/agendamento-financeiro
 - andrelemos2/restwebservices
 - andrelemos2/vote-no-restaurante
 - andrelemos2/votenorestaurante_spring
 - andrelemos2/alurapic-angularjs
 - andrelemos2/filmes-angularjs
 - andrelemos2/agendamentofinanceiro-spring
 - andrelemos2/StockWatcherSample
 - andrelemos2/consumowebservicesnfe_factorymethod
 - andrelemos2/java-design-patterns

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/7106721/andre-lemos
   flairimageurl: https://i.stack.imgur.com/RrRPI.jpg?s=64&g=1

#Mobile apps section is optional
apps:
 - name: 
   platform: 
   url: 
   description: 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate), GWT in addition to others.  In my current role Java is the primary language used - and I am familiar with many of the languages features and quirks. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework (although current role uses ColdFusion for server side web stack). I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as Backbone/Underscore/Require.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/Parse. <br/><br/>
