# Site settings
title: Andre Lemos
twitter_username: andrelemos2
name: Andre Lemos

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://andrelemos2.blogspot.com.br/
 - title: GitHub
   url: https://github.com/andrelemos2
 - title: LinkedIn
   url: https://br.linkedin.com/in/andre-lemos-9b16b924

#Any buzzword skills you want to include
skills:
 - Spring MVC
 - Spring Boot
 - Java
 - JPA
 - SQL
 - REST
 - GWT
 - SmartGWT

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://andrelemos2.blogspot.com.br

#Work experience is required
roles:
 - title: Java Developer
   start: 2016
   end: Ongoing
   employer: Reserva Facil S/A
   description: The Reserva Facil simplifies the daily travel agent and corporate clients in job search, booking and issuing airline tickets, travel assistance and hospitality. agile and versatile tool, the RF offers advanced technology and ample resources, able to serve its customers in all its expectations. Quickly and safely, the user receives information about the best prices in real time, provided directly by air suppliers, hotels and travel assistance. Your system also has several features that help the corporate client travel management as multiple cost centers, travel policy, travel policy report, among others.
 - title: Java Developer
   start: 2010
   end: 2016
   employer: Openbravo Brazil (Disoft Solutions S/A)
   description: Openbravo is the world leader in open source systems for retail, supporting medium and large enterprises around the world to manage, continuously, increasingly rapid transformations taking place in the retail world of today. Openbravo Commerce Suite, a multi-channel solution for retail, allows retailers to manage comprehensively your business and deliver a great shopping experience for customers in-store, in addition to enabling a business differentiation due to a technological platform for the highly flexible, scalable retail, already in the cloud and accessible from any mobile device.
 - title: Junior Java Developer
   start: 2008
   end: 2010
   employer: Vipware Informatica Ltda
   description: The VIPware came up with the goal of helping people not experts in technology, but who need it to perform their duties with excellence and prosperity. Simply understanding the needs, evaluating the available technological resources, and offering a range of services to achieve the common objectives pursued in relation to cost, schedule, and results.

#Education is required
education:
 - level: Bachelor of Information Systems
   date: 2010
   subject: Product development and service Information Systems (IT)
   school: Bandeirante University of Sao Paulo

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/545e0dd32bcfe728cb90b48c953c917a
   courses:
    - title: Orientation object with Java
      link: https://www.coursera.org/learn/orientacao-a-objetos-com-java/home
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/9c/b444f0c97311e588123d50ccb31597/Modified--IconFinder--1454414808_1416364765_java_coffee_x_cup_application.png?auto=format&dpr=1&w=80&h=80&fit=fill&bg=FFF
      date: July 11, 2016
    - title: Introduction to Philosofy
      link: https://www.coursera.org/learn/philosophy/home/welcome
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/topics/introphil/large-icon.png?auto=format&dpr=1&w=80&h=80&fit=fill&bg=FFF
      date: August 10, 2016

#List of interesting Github repo/projects to include - optional
github:
 - andrelemos2/learntoredux
 - andrelemos2/agendamento-financeiro
 - andrelemos2/restwebservices
 - andrelemos2/vote-no-restaurante
 - andrelemos2/votenorestaurante_spring
 - andrelemos2/alurapic-angularjs
 - andrelemos2/filmes-angularjs
 - andrelemos2/agendamentofinanceiro-spring
 - andrelemos2/StockWatcherSample
 - andrelemos2/consumowebservicesnfe_factorymethod
 - andrelemos2/java-design-patterns

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/7106721/andre-lemos
   flairimageurl: http://stackoverflow.com/users/flair/7106721.png

#Mobile apps section is optional
apps:
 - name: 
   platform: 
   url: 
   description: 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate), GWT in addition to others.  In my current role Java is the primary language used - and I am familiar with many of the languages features and quirks. <br/><br/>
   <strong>Web Development</strong>: My server side web development experience has largely been based on the Spring MVC framework. I have also worked with some client side technology, having used jQuery, Bootstrap, LESS, SASS and have also experimented with other interesting technologies such as AngularJS/ReactJS/Redux.<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven and Jenkins. I have experience with an array of testing tools and technologies.<br/><br/>